title: Mrs. Wei's Portfolio # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my portfolio site showcasing my works from my web design class. 
  <br><br>
  <br><br>
  <br><br>
  Please contact me if you would like me to create a website for you or your company.  
  <br><br>
  
theme: jekyll-theme-leap-day
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
